name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cargo-check:
    name: Cargo Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Cargo check
        run: cargo check
